### ISSUE TITLE
ht_icon:22:50: error: narrowing conversion of '247' from 'int' to 'char'

### ISSUE THREAD

**Issue by billpage** [GabrielDosReis/open-axiom#2]
On [SMC](https://cloud.sagemath.com/projects/77750c71-ec7b-4962-bf55-a49ff5065fb6)

```
~/open-axiom-build$ g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
~/open-axiom-build$ ../open-axiom/configure --prefix=$HOME
~/open-axiom-build$ make 2>&1 | cat > make.log & 
```

[make.zip](https://github.com/GabrielDosReis/open-axiom/files/96452/make.zip)

```
libtool: compile:  g++ -c -m64 -D_GNU_SOURCE -std=c++11 -g -O2 -O2 -Wall -std=c++11 -g -O2 -O2 -Wall -I../../../open-axiom/src/include -I../../config -I. ../../../open-axiom/src/hyper
/initx.c  -fPIC -DPIC -o .libs/initx.o
In file included from ../../../open-axiom/src/hyper/initx.c:63:0:
../../../open-axiom/src/hyper/ht_icon:22:50: error: narrowing conversion of '247' from 'int' to 'char'
 inside { } [-Wnarrowing]
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
                                                  ^
../../../open-axiom/src/hyper/ht_icon:22:50: error: narrowing conversion of '231' from 'int' to 'char' inside { } [-Wnarrowing]
```

**Comment by GabrielDosReis** [comment]
Thanks!  Igor Pashev reported the issue, but didn't get around to fix it.This is because of new C++11 language rules (which the truly yours put there.)Will fix it when I get access to my linux box-------- Original message --------From: Bill Page notifications@github.com Date: 1/19/2016  2:30 PM  (GMT-05:00) To: GabrielDosReis/open-axiom open-axiom@noreply.github.com Subject: [open-axiom] ht_icon:22:50: error: narrowing conversion of '247' from
  'int' to 'char' (#2) 
On SMC

~/open-axiom-build$ g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
~/open-axiom-build$ ../open-axiom/configure --prefix=$HOME
~/open-axiom-build$ make 2>&1 | cat > make.log & 

make.zip

libtool: compile:  g++ -c -m64 -D_GNU_SOURCE -std=c++11 -g -O2 -O2 -Wall -std=c++11 -g -O2 -O2 -Wall -I../../../open-axiom/src/include -I../../config -I. ../../../open-axiom/src/hyper
/initx.c  -fPIC -DPIC -o .libs/initx.o
In file included from ../../../open-axiom/src/hyper/initx.c:63:0:
../../../open-axiom/src/hyper/ht_icon:22:50: error: narrowing conversion of '247' from 'int' to 'char'
 inside { } [-Wnarrowing]
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
                                                  ^
../../../open-axiom/src/hyper/ht_icon:22:50: error: narrowing conversion of '231' from 'int' to 'char' inside { } [-Wnarrowing]

**Comment by GabrielDosReis** [comment]
Fixed by https://github.com/GabrielDosReis/open-axiom/commit/ffe9a032601ffb59a10141bce13b4322a1584e87
